### ISSUE TITLE
missing tp.Dcc.managers.plugins 

### ISSUE THREAD

**Issue by qeeji** [tpDcc/tpDcc-core#2]
Hi Tomas , 

Repoart an issue when I tried to run this tool , please refer to the error showed in maya script editor , thanks ! 
# Error: ImportError: file G:/xM/Dropbox/hzWork/hzNet/hzTools/libs/tpDcc/tpDcc\managers\libs.py line 23: cannot import name plugins # 

Cheers,

**Comment by tpoveda** [comment]
Thank you for reporting this. I will check it asap. @qeeji  Are you running latest released version code or are you running master branch code?

**Comment by tpoveda** [comment]
Bug should be fixed if you pull latest changes from master branch.
